name: GLaDOS-CheckIn
on:
  push:
    branches: [ master ]
  schedule:
    - cron: 30 1 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install axios
        run: npm install axios
      - name: CheckIn
        run: node checkin.js 
        env:
          SCKEY: ${{ secrets.SCKEY }}
          COOKIE: ${{ secrets.COOKIE }}
