# This is a basic workflow to help you get started with Actions

name: GladosCheckIn

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
  - cron: 0 0 * * *
